@startuml
skinparam activity {
  BackgroundColor<< Dev >> LightSkyBlue
}

(*) --> "C# base"
note left
"Nuget"
"Object, class, struct, type"
"Collections, generics, LINQ"
"Exceptions, debug"
end note

"C# base" --> "C# Advanced"

(*) --> "Tools: IDE, extensions"
"Tools: IDE, extensions" --> "C# Advanced"

(*) --> "Git/Github"
"Git/Github" --> "C# Advanced"

"Git/Github" --> "CI: Github actions, azure pipeline"
"Git/Github" --> "Git flow"

"C# Advanced" --> "Common libs"
"Common libs" --> "Testing"
"Common libs" --> "Logging"
"Common libs" --> "Objects mapping"

"C# Advanced" --> "OOD"
note left
Clean code, SOLID
UML
Patterns
end note

"C# Advanced" --> "Базы данных"
note right
SQL
ADO.NET
ORM, EF
end note

"OOD" --> Frameworks
"Базы данных" --> Frameworks

Frameworks --> ".NET in deep"
note left
GC
CLR, CTS, CLS, CIL
Reflection
end note

--> "Многопоточка, асинхронность"
note left
Thread
Thread pool
Sync primitives
Task, async
PLINQ
end note
--> ".Кровавый энтерпрайз" << Dev >>

Frameworks --> "Xamarin"
--> "MAUI"
--> "Mobile dev" << Dev >>

Frameworks --> "WPF/UWP"
--> "MVVM"
--> "ReactiveUI"
--> "Desktop dev" << Dev >>

Frameworks --> "ASP"
note left
DI
Swagger
Middlewares
HTTP, REST
HATEAOS
Caching
FluentValidator
end note

"ASP" --> "Blazzor"
"Blazzor" --> "Fullstack dev" << Dev >>

"ASP" --> "Microservices"
note left
Polly
RabbitMQ
SignalR
Docker
Gateway, Tye
end note
"Microservices" --> "Backend dev" << Dev >>

@enduml

' ```plantuml
' @startmindmap

' * C# base
' ** Тулинг: IDE, git, Github
' ***_ Issue, pull request, review
' ***_ Git flow
' ***_ Advanced git commands: merge, rebase
' ***_ CI: Github actions, azure pipeline

' **_ Nuget
' **_ Object, class, struct, type
' **_ Collections, generics, LINQ
' **_ Exceptions, debug

' ** C# advanced

' *** OOD
' ****_ Clean code, SOLID
' ****_ UML
' ****_ Patterns
' **** Базы данных
' *****_ SQL
' *****_ ADO.NET
' *****_ ORM: EntityFramework

' *** Common
' ****_ Testing
' ****_ Logging framework
' ****_ Objects mapping

' *** ASP.NET
' ****_ Controller/Service/Repository
' ****_ DI
' ****_ Swagger
' ****_ Middlewares
' ****_ HTTP, REST, HATEAOS
' ****_ Caching
' ****_ FluentValidator

' **** Microservices
' *****_ Polly
' *****_ RabbitMQ
' *****_ SignalR
' *****_ Docker
' *****_ Gateway, Tye
' *****[#lightgreen] Backend dev

' **** Blazor
' *****[#lightgreen] Fullstack dev

' *** WPF/UWP
' ****_ User control
' ****_ Resources
' ****_ MVVM
' ****_ ReactiveUI
' ****[#lightgreen] Desktop UI dev

' *** Xamarin
' **** MAUI
' *****[#lightgreen] Mobile dev


' *** C# in deep
' ****_ GC
' ****_ CLR, CTS, CLS, CIL
' ****_ Reflection
' **** Многопоточка, асинхронность
' *****_ Thread, Thread pool
' *****_ Monitor, lock, ResetEvent
' *****_ Task, async
' *****_ PLINQ
' *****[#lightgreen] "Кровавый энтерпрайз" dev

' @endmindmap
' ```